dataset:
  target: datasets.realsr.RealAllScalesSRDataset
  params:
    preload: False
    camera_types: [Canon] # [Canon, Nikon]
    patch_size: 256
    augmentation: True
    test: False
    dataroot: 'Path_to_RealSR_dataset_root_directory'

data_loader:
  batch_size: 16
  shuffle: True
  persistent_workers: True
  num_workers: 16
  drop_last: False

repeat_dataset:
  times: 10000

batch_transform:
  target: datasets.batch_transform.IdentityBatchTransform